import java.util.Scanner;

public class exercicio4 {public static void main(String[] args) {
    Scanner leitor = new Scanner (System.in);
    System.out.println( "escreva quatro numeros ");
    int n1= leitor.nextInt(),n2 = leitor.nextInt(), n3 = leitor.nextInt(), n4 = leitor.nextInt();
    int s1 = n1 + n1;
    int s2 = n1 + n2;
    int s3 = n1 + n3;
    int s4 = n1 + n4;
    int o1 = n2 + n1;
    int o2 = n2 + n2;
    int o3 = n2 + n3;
    int o4 = n2 + n4;
    int m1 = n3 + n1;
    int m2 = n3 + n2;
    int m3 = n3 + n3;
    int m4 = n3 + n4;
    int a1 = n4 + n1;
    int a2 = n4 + n2;
    int a3 = n4 + n3;
    int a4 = n4 + n4;
    System.out.println("valor da soma desse numeros com o primeiro termo  é respectivamente");
    System.out.println(s1);
    System.out.println(s2);
    System.out.println(s3);
    System.out.println(s4);
    System.out.println("a soma desses numeros com o segundo termo é respectivamente");
    System.out.println(o1);
    System.out.println(o2);
    System.out.println(o3);
    System.out.println(o4);
    System.out.println("a soma dos numeros com o terceiro termo é respectivamente");
    System.out.println(m1);
    System.out.println(m2);
    System.out.println(m3);
    System.out.println(m4);
    System.out.println("a soma dos numeros com o quarto termo é respectivamente");
    System.out.println(a1);
    System.out.println(a2);
    System.out.println(a3);
    System.out.println(a4);
    int mults1 = n1 * n1;
    int mults2 = n1 * n2;
    int mults3 = n1 * n3;
    int mults4 = n1 * n4;
    int multo1 = n2 * n1;
    int multo2 = n2 * n2;
    int multo3 = n2 * n3;
    int multo4 = n2 * n4;
    int multm1 = n3 * n1;
    int multm2 = n3 * n2;
    int multm3 = n3 * n3;
    int multm4 = n3 * n4;
    int multa1 = n4 * n1;
    int multa2 = n4 * n2;
    int multa3 = n4 * n3;
    int multa4 = n4 * n4;
    System.out.println("o valor da multiplição desse numeros com o primeiro termo  é respectivamente");
    System.out.println(mults1);
    System.out.println(mults2);
    System.out.println(mults3);
    System.out.println(mults4);
    System.out.println("o valor da multiplição   desses numeros com o segundo termo é respectivamente");
    System.out.println(multo1);
    System.out.println(multo2);
    System.out.println(multo3);
    System.out.println(multo4);
    System.out.println("o valor da multiplição  dos numeros com o terceiro termo é respectivamente");
    System.out.println(multm1);
    System.out.println(multm2);
    System.out.println(multm3);
    System.out.println(multm4);
    System.out.println("o valor da multiplição   dos numeros com o quarto termo é respectivamente");
    System.out.println(multa1);
    System.out.println(multa2);
    System.out.println(multa3);
    System.out.println(multa4);
}
}
